name: .NET Core CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter Tag to use for the build'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0' # or your project's .NET version

    - name: Restore dependencies
      run: dotnet restore NVL9.DSM.WebAPITest/NVL9.DSM.WebAPITest.csproj

    - name: Build
      run: dotnet build NVL9.DSM.WebAPITest/NVL9.DSM.WebAPITest.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test NVL9.DSM.WebAPITest/NVL9.DSM.WebAPITest.csproj --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish NVL9.DSM.WebAPITest/NVL9.DSM.WebAPITest.csproj --configuration Release --output ./output